name: Main Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: dotnet restore ./YaCloudKit.sln

      - name: Build
        run: dotnet build ./YaCloudKit.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build ./YaCloudKit.sln --configuration Release --no-restore

      - name: Pack
        run: dotnet pack ./YaCloudKit.sln -c Release

      - name: Publish
        run: dotnet nuget push **/*.nupkg --skip-duplicate -k ${{secrets.NUGET_TOKEN}} -s https://api.nuget.org/v3/index.json
