name: Main Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Install dependencies
        run: dotnet restore ./src/YaCloudKit.sln

      - name: Build
        run: dotnet build ./src/YaCloudKit.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test ./src/YaCloudKit.sln --configuration Release --no-restore

      - name: Pack YaCloudKit.MQ
        run: dotnet pack ./src/MessageQueue/YaCloudKit.MQ/YaCloudKit.MQ.csproj -c Release -p:BuildNumber=${{ github.run_number }}

      - name: Publish YaCloudKit.MQ
        run: dotnet nuget push **/YaCloudKit.MQ/**/YaCloudKit.MQ.*.nupkg -k ${{secrets.NUGET_TOKEN}} -s https://api.nuget.org/v3/index.json
