name: Pull Request

on: pull_request

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Run unit tests
    env:
      DOCKER_BUILDKIT: 1
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: dotnet restore ./YaCloudKit.sln

      - name: Build
        run: dotnet build ./YaCloudKit.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build ./YaCloudKit.sln --configuration Release --no-restore